### ISSUE TITLE
[mininasm] readme typo

### ISSUE THREAD

**Issue by roytam1** [pts/owccdos#8]
since mininasm has no issue tracker, I have to create an issue here.

in README, there is a line:
````
* Only `db', `dw' and `dq' are the supported data instructions (so no `dq'
  or `dt').
````

I think the first `dq` should be `dw`.

BTW I put dosmc compiled mininasm.c (rev d97a517) here for information:
[mininasm-rev-d97a517.zip](https://github.com/pts/dosmc/files/13764090/mininasm-rev-d97a517.zip)
minnnasm.com compiled with binary above produces identical binary as mininasm-v6.com.

**Comment by pts** [comment]
I've fiixed it in https://github.com/pts/mininasm/commit/200d7e53524cf4d9a3a7a3203c502a83628ffed9 , thanks! I've also enabled the issue tracker https://github.com/pts/mininasm/issues.
